### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takumi19910112** [takumi19910112/furima-38533#13]
自身のフリマアプリのURL | 本番環境(Heroku)のURL
https://furima-38533.herokuapp.com/
Basic認証のIDとパスワード |  
id:admin password:2222
出品者用のメールアドレスとパスワード | 本番環境で使用可能なユーザーの情報
email:takumi_shuppin@gmail.com     password:takumi0112
購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
email:takumi_konyu@gmail.com     password:takumi0112

**Comment by shodai-ito** [comment]
@takumi19910112 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`商品購入機能`**
- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
下記のカード情報を入力しても「Token can't be blank」となってしまい購入ができませんでした。
```
【カード情報】
・カード番号：4242424242424242
・有効期限：今日より未来の日付
・セキュリティコード：123
```

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@takumi19910112 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![lgtm_01](https://user-images.githubusercontent.com/65059944/198941809-37754604-75ba-42ef-9b30-11f0b840f8b9.png)
